title: Self-Evolving Embodied Agents Group
description: Our mission is to establish a complete pipeline for creating self-evolving embodied agents.
baseurl: "/Self-Evolving-Embodied-Agents-Group" # the subpath of your site, e.g. /blog
url: "https://N50s.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
